config/routes.rb
Rails.application.routes.draw do

  resources :todos

  root to: "todos#index"

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = Todo.new
    @todos = Todo.all
  end

  def create
    @todo = Todo.create(todo_params)
    redirect_to '/'
  end

  def show

  end

  def destroy
    todo(params[:id]).destroy
    redirect_to '/'
  end



  private
  def todo_params
    params.require(:todo).permit(:description, :text)
  end

  def todo(todo_id)
    Todo.find(todo_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<div class="todo-container">
  <%= form_for :todo do |f|  %>
    <%= f.text_field :description, placeholder: "What needs to be done BOI", id:"todo-box" %>
  <% end %>
  <br>
  <% @todos.each do |todo| %>
    <ul>
      <%= todo.description %>
      <%= form_tag(todo_path(todo), method: :delete) do %>
        <%= submit_tag 'Destroy'%>
      <% end %>
    </ul>
  <% end %>
</div>